In [1]:
import panda as pd

<class 'ModuleNotFoundError'>: No module named 'panda'

In [2]:
install pandas

<class 'SyntaxError'>: invalid syntax (<ipython-input-2-732390c53970>, line 1)

In [3]:
!pip install pandas

<class 'OSError'>: Not available

In [3]:
import pandas as pd
print(pd.__version__)

2.3.2

In [6]:
# create data frame
df=pd.DataFrame([1,2,3,4],columns=['col_name'])
print(df)

   col_name
0         1
1         2
2         3
3         4

In [7]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [8]:
data={
    'name':['ganesh','naik','nikki','mikki','gaike','gowda'],
    'age':[13,34,55,33,32,44],
    'salary':[20000,33000,4500,5000,3444,3443],
    'experiance':[1,2,3,2,1,5]
}

In [9]:
df=pd.DataFrame(data)
print(df)

     name  age  salary  experiance
0  ganesh   13   20000           1
1    naik   34   33000           2
2   nikki   55    4500           3
3   mikki   33    5000           2
4   gaike   32    3444           1
5   gowda   44    3443           5

### ***Basic underStanding***

In [10]:
df.columns

Index(['name', 'age', 'salary', 'experiance'], dtype='object')

In [14]:
df.shape

(6, 4)

In [15]:
df.head

<bound method NDFrame.head of      name  age  salary  experiance
0  ganesh   13   20000           1
1    naik   34   33000           2
2   nikki   55    4500           3
3   mikki   33    5000           2
4   gaike   32    3444           1
5   gowda   44    3443           5>

In [16]:
df.head(3)

     name  age  salary  experiance
0  ganesh   13   20000           1
1    naik   34   33000           2
2   nikki   55    4500           3

In [17]:
df.tail

<bound method NDFrame.tail of      name  age  salary  experiance
0  ganesh   13   20000           1
1    naik   34   33000           2
2   nikki   55    4500           3
3   mikki   33    5000           2
4   gaike   32    3444           1
5   gowda   44    3443           5>

In [18]:
df.tail(2)

    name  age  salary  experiance
4  gaike   32    3444           1
5  gowda   44    3443           5

In [20]:
print(type(df))
print(type(data))

<class 'pandas.core.frame.DataFrame'>
<class 'dict'>

#### ***rename()***

In [21]:
df.rename(columns={'salary':'Monthly-income'})

     name  age  Monthly-income  experiance
0  ganesh   13           20000           1
1    naik   34           33000           2
2   nikki   55            4500           3
3   mikki   33            5000           2
4   gaike   32            3444           1
5   gowda   44            3443           5

### ***result shown but not Changed***

In [22]:
df

     name  age  salary  experiance
0  ganesh   13   20000           1
1    naik   34   33000           2
2   nikki   55    4500           3
3   mikki   33    5000           2
4   gaike   32    3444           1
5   gowda   44    3443           5

### **Change in dataFrame use inplace=True default is False**

In [24]:
df.rename(columns={'salary':'Monthly-income'},inplace=True)

In [25]:
df

     name  age  Monthly-income  experiance
0  ganesh   13           20000           1
1    naik   34           33000           2
2   nikki   55            4500           3
3   mikki   33            5000           2
4   gaike   32            3444           1
5   gowda   44            3443           5

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            6 non-null      object
 1   age             6 non-null      int64
 2   Monthly-income  6 non-null      int64
 3   experiance      6 non-null      int64
dtypes: int64(3), object(1)
memory usage: 240.0+ bytes

In [28]:
df.describe()

             age  Monthly-income  experiance
count   6.000000         6.00000    6.000000
mean   35.166667     11564.50000    2.333333
std    13.991664     12292.59471    1.505545
min    13.000000      3443.00000    1.000000
25%    32.250000      3708.00000    1.250000
50%    33.500000      4750.00000    2.000000
75%    41.500000     16250.00000    2.750000
max    55.000000     33000.00000    5.000000

## **Save and Load Data from csv**

In [34]:
df.to_csv('Test_data.csv',index=False)

In [35]:
load_df=pd.read_csv('Test_data.csv')

In [36]:
load_df

     name  age  Monthly-income  experiance
0  ganesh   13           20000           1
1    naik   34           33000           2
2   nikki   55            4500           3
3   mikki   33            5000           2
4   gaike   32            3444           1
5   gowda   44            3443           5

### ***Rows And Columns Slection***

In [58]:
## Select columns
df[['name']]
df[['name','Monthly-income']]
df.rename(columns={'Monthly-income':'salary'},inplace=True)

In [59]:
#select rows
#3 loc[df.columns_name=='Value']
df.loc[df.name=='gaike']

    name  age  salary  experiance
4  gaike   32    3444           1

### loc-with conditions
## df.loc[(df.columns_name=='value') & (df.columns_name<=(condition)

In [60]:
df.loc[(df.name=='naik') & (df.age>=18)]

   name  age  salary  experiance
1  naik   34   33000           2

In [61]:
df.loc[(df.name=='ganesh') & (df.experiance>=0)]

     name  age  salary  experiance
0  ganesh   13   20000           1

### index based iloc

In [62]:
## iloc - index-value based
df.iloc[0]
df.iloc[1]

name           naik
age              34
salary        33000
experiance        2
Name: 1, dtype: object

In [63]:
df.iloc[1:2]

   name  age  salary  experiance
1  naik   34   33000           2

In [64]:
df.iloc[0:3]

     name  age  salary  experiance
0  ganesh   13   20000           1
1    naik   34   33000           2
2   nikki   55    4500           3

In [65]:
df.loc[1:2] #[start:stop:step]

    name  age  salary  experiance
1   naik   34   33000           2
2  nikki   55    4500           3

In [66]:
df.loc[0:2:2]

     name  age  salary  experiance
0  ganesh   13   20000           1
2   nikki   55    4500           3

### **filter Data-Frame**

In [67]:
df['age']>18

0    False
1     True
2     True
3     True
4     True
5     True
Name: age, dtype: bool

In [68]:
df['age']>30

0    False
1     True
2     True
3     True
4     True
5     True
Name: age, dtype: bool

In [69]:
df[df['age']>=35]

    name  age  salary  experiance
2  nikki   55    4500           3
5  gowda   44    3443           5

In [73]:
df[(df['age']>=20) & (df['salary']>=3500)]

    name  age  salary  experiance
1   naik   34   33000           2
2  nikki   55    4500           3
3  mikki   33    5000           2

In [74]:
df_age_filter=df[df['age']>=35]
df_age_filter

    name  age  salary  experiance
2  nikki   55    4500           3
5  gowda   44    3443           5

In [75]:
df.where(df['age']>=35)

    name   age  salary  experiance
0    NaN   NaN     NaN         NaN
1    NaN   NaN     NaN         NaN
2  nikki  55.0  4500.0         3.0
3    NaN   NaN     NaN         NaN
4    NaN   NaN     NaN         NaN
5  gowda  44.0  3443.0         5.0

In [76]:
df.where(df['age']>=35 , other='Not Eligible')

           name           age        salary    experiance
0  Not Eligible  Not Eligible  Not Eligible  Not Eligible
1  Not Eligible  Not Eligible  Not Eligible  Not Eligible
2         nikki            55          4500             3
3  Not Eligible  Not Eligible  Not Eligible  Not Eligible
4  Not Eligible  Not Eligible  Not Eligible  Not Eligible
5         gowda            44          3443             5

#### ***Rows and Columns - Operations (Add, Update, Delete)***

In [77]:
df

     name  age  salary  experiance
0  ganesh   13   20000           1
1    naik   34   33000           2
2   nikki   55    4500           3
3   mikki   33    5000           2
4   gaike   32    3444           1
5   gowda   44    3443           5

In [78]:
#3 Add new Columns....
df['Team']=['CEO','HR','CTO','DA','MANAGER','DEAN']

In [79]:
df

     name  age  salary  experiance     Team
0  ganesh   13   20000           1      CEO
1    naik   34   33000           2       HR
2   nikki   55    4500           3      CTO
3   mikki   33    5000           2       DA
4   gaike   32    3444           1  MANAGER
5   gowda   44    3443           5     DEAN

In [80]:
## adding new columns by the multiple of anycolumns
df['bonus']=df['salary']*0.2
df

     name  age  salary  experiance     Team   bonus
0  ganesh   13   20000           1      CEO  4000.0
1    naik   34   33000           2       HR  6600.0
2   nikki   55    4500           3      CTO   900.0
3   mikki   33    5000           2       DA  1000.0
4   gaike   32    3444           1  MANAGER   688.8
5   gowda   44    3443           5     DEAN   688.6

In [84]:
df['increment']=df['bonus']+df['salary']
df

     name  age  salary  experiance     Team   bonus  increment
0  ganesh   13   20000           1      CEO  4000.0    24000.0
1    naik   34   33000           2       HR  6600.0    39600.0
2   nikki   55    4500           3      CTO   900.0     5400.0
3   mikki   33    5000           2       DA  1000.0     6000.0
4   gaike   32    3444           1  MANAGER   688.8     4132.8
5   gowda   44    3443           5     DEAN   688.6     4131.6

In [85]:
## Addd New Rows
df.loc[len(df)]=['ABC',32,20300,2,'DTO',20300*0.2,20300+20300*0.2]

In [86]:
df

     name  age  salary  experiance     Team   bonus  increment
0  ganesh   13   20000           1      CEO  4000.0    24000.0
1    naik   34   33000           2       HR  6600.0    39600.0
2   nikki   55    4500           3      CTO   900.0     5400.0
3   mikki   33    5000           2       DA  1000.0     6000.0
4   gaike   32    3444           1  MANAGER   688.8     4132.8
5   gowda   44    3443           5     DEAN   688.6     4131.6
6     ABC   32   20300           2      DTO  4060.0    24360.0

In [88]:
## update value
df.loc[4,'experiance']=4
df

     name  age  salary  experiance     Team   bonus  increment
0  ganesh   13   20000           1      CEO  4000.0    24000.0
1    naik   34   33000           2       HR  6600.0    39600.0
2   nikki   55    4500           3      CTO   900.0     5400.0
3   mikki   33    5000           2       DA  1000.0     6000.0
4   gaike   32    3444           4  MANAGER   688.8     4132.8
5   gowda   44    3443           5     DEAN   688.6     4131.6
6     ABC   32   20300           2      DTO  4060.0    24360.0

In [89]:
## update value - using columns value
df.loc[df.name=='mikki','experiance']=0
df

     name  age  salary  experiance     Team   bonus  increment
0  ganesh   13   20000           1      CEO  4000.0    24000.0
1    naik   34   33000           2       HR  6600.0    39600.0
2   nikki   55    4500           3      CTO   900.0     5400.0
3   mikki   33    5000           0       DA  1000.0     6000.0
4   gaike   32    3444           4  MANAGER   688.8     4132.8
5   gowda   44    3443           5     DEAN   688.6     4131.6
6     ABC   32   20300           2      DTO  4060.0    24360.0

In [90]:
## delete value- rows and columns
df.drop(df[df.name=='ABC'].index) ## drop rows axis=0

     name  age  salary  experiance     Team   bonus  increment
0  ganesh   13   20000           1      CEO  4000.0    24000.0
1    naik   34   33000           2       HR  6600.0    39600.0
2   nikki   55    4500           3      CTO   900.0     5400.0
3   mikki   33    5000           0       DA  1000.0     6000.0
4   gaike   32    3444           4  MANAGER   688.8     4132.8
5   gowda   44    3443           5     DEAN   688.6     4131.6

In [91]:
df[df.name=='ABC']

  name  age  salary  experiance Team   bonus  increment
6  ABC   32   20300           2  DTO  4060.0    24360.0

In [92]:
## it drop of static on 
## if you wnat df=df.drop('columns_name',
df.drop('increment',axis=1)

     name  age  salary  experiance     Team   bonus
0  ganesh   13   20000           1      CEO  4000.0
1    naik   34   33000           2       HR  6600.0
2   nikki   55    4500           3      CTO   900.0
3   mikki   33    5000           0       DA  1000.0
4   gaike   32    3444           4  MANAGER   688.8
5   gowda   44    3443           5     DEAN   688.6
6     ABC   32   20300           2      DTO  4060.0

In [94]:
df.drop(['bonus','Team'],axis=1) # delete multiple columns

     name  age  salary  experiance  increment
0  ganesh   13   20000           1    24000.0
1    naik   34   33000           2    39600.0
2   nikki   55    4500           3     5400.0
3   mikki   33    5000           0     6000.0
4   gaike   32    3444           4     4132.8
5   gowda   44    3443           5     4131.6
6     ABC   32   20300           2    24360.0

In [95]:
df

     name  age  salary  experiance     Team   bonus  increment
0  ganesh   13   20000           1      CEO  4000.0    24000.0
1    naik   34   33000           2       HR  6600.0    39600.0
2   nikki   55    4500           3      CTO   900.0     5400.0
3   mikki   33    5000           0       DA  1000.0     6000.0
4   gaike   32    3444           4  MANAGER   688.8     4132.8
5   gowda   44    3443           5     DEAN   688.6     4131.6
6     ABC   32   20300           2      DTO  4060.0    24360.0

### ***Sorting***

In [96]:
df.sort_values('salary') ### Ascending order

     name  age  salary  experiance     Team   bonus  increment
5   gowda   44    3443           5     DEAN   688.6     4131.6
4   gaike   32    3444           4  MANAGER   688.8     4132.8
2   nikki   55    4500           3      CTO   900.0     5400.0
3   mikki   33    5000           0       DA  1000.0     6000.0
0  ganesh   13   20000           1      CEO  4000.0    24000.0
6     ABC   32   20300           2      DTO  4060.0    24360.0
1    naik   34   33000           2       HR  6600.0    39600.0

In [97]:
df.sort_values('salary',ascending=False) ##3 Descending order

     name  age  salary  experiance     Team   bonus  increment
1    naik   34   33000           2       HR  6600.0    39600.0
6     ABC   32   20300           2      DTO  4060.0    24360.0
0  ganesh   13   20000           1      CEO  4000.0    24000.0
3   mikki   33    5000           0       DA  1000.0     6000.0
2   nikki   55    4500           3      CTO   900.0     5400.0
4   gaike   32    3444           4  MANAGER   688.8     4132.8
5   gowda   44    3443           5     DEAN   688.6     4131.6

## ***Working with Date Value***

In [109]:
df['DOJ'] =['2024-01-23','2023-11-03','2025-03-12','2026-05-25','2022-04-29','2023-08-13','2021-9-03']

In [110]:
df

     name  age  salary  experiance     Team   bonus  increment         DOJ
0  ganesh   13   20000           1      CEO  4000.0    24000.0  2024-01-23
1    naik   34   33000           2       HR  6600.0    39600.0  2023-11-03
2   nikki   55    4500           3      CTO   900.0     5400.0  2025-03-12
3   mikki   33    5000           0       DA  1000.0     6000.0  2026-05-25
4   gaike   32    3444           4  MANAGER   688.8     4132.8  2022-04-29
5   gowda   44    3443           5     DEAN   688.6     4131.6  2023-08-13
6     ABC   32   20300           2      DTO  4060.0    24360.0   2021-9-03

In [111]:
df['DOJ'].dtype

dtype('O')

In [113]:
df['DOJ']=pd.to_datetime(df['DOJ'])
df['DOJ'].dtype

dtype('<M8[ns]')

In [118]:
df1=df
df1['lDay']=['23-01-2024','03-11-2023','12-03-2025','25-05-2026','29-04-2022','13-08-2023','03-9-2021']
df1['lDay'].dtype

dtype('O')

In [128]:

df

     name  age  salary  experiance     Team   bonus  increment        DOJ
0  ganesh   13   20000           1      CEO  4000.0    24000.0 2024-01-23
1    naik   34   33000           2       HR  6600.0    39600.0 2023-11-03
2   nikki   55    4500           3      CTO   900.0     5400.0 2025-03-12
3   mikki   33    5000           0       DA  1000.0     6000.0 2026-05-25
4   gaike   32    3444           4  MANAGER   688.8     4132.8 2022-04-29
5   gowda   44    3443           5     DEAN   688.6     4131.6 2023-08-13
6     ABC   32   20300           2      DTO  4060.0    24360.0 2021-09-03

In [119]:
df1['lDay']=pd.to_datetime(df1['lDay'])

<ipython-input-119-38fa25e872a9>:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df1['lDay']=pd.to_datetime(df1['lDay'])

In [120]:
df1['lDay'].dtype

dtype('<M8[ns]')

In [121]:
df1

,name,age,salary,experiance,Team,bonus,increment,DOJ,lDay
0,ganesh,13,20000,1,CEO,4000.0,24000.0,2024-01-23,2024-01-23
1,naik,34,33000,2,HR,6600.0,39600.0,2023-11-03,2023-11-03
2,nikki,55,4500,3,CTO,900.0,5400.0,2025-03-12,2025-03-12
3,mikki,33,5000,0,DA,1000.0,6000.0,2026-05-25,2026-05-25
4,gaike,32,3444,4,MANAGER,688.8,4132.8,2022-04-29,2022-04-29
5,gowda,44,3443,5,DEAN,688.6,4131.6,2023-08-13,2023-08-13
6,ABC,32,20300,2,DTO,4060.0,24360.0,2021-09-03,2021-09-03

In [129]:
df.columns

Index(['name', 'age', 'salary', 'experiance', 'Team', 'bonus', 'increment',
       'DOJ'],
      dtype='object')

In [130]:
df

     name  age  salary  experiance     Team   bonus  increment        DOJ
0  ganesh   13   20000           1      CEO  4000.0    24000.0 2024-01-23
1    naik   34   33000           2       HR  6600.0    39600.0 2023-11-03
2   nikki   55    4500           3      CTO   900.0     5400.0 2025-03-12
3   mikki   33    5000           0       DA  1000.0     6000.0 2026-05-25
4   gaike   32    3444           4  MANAGER   688.8     4132.8 2022-04-29
5   gowda   44    3443           5     DEAN   688.6     4131.6 2023-08-13
6     ABC   32   20300           2      DTO  4060.0    24360.0 2021-09-03

### ***Date Based Operations monthly Comparition***

In [136]:
## '''extract year month weekly day........
df['DOJ'].dt.year
df['DOJ'].dt.month
df['DOJ'].dt.day
df['DOJ'].dt.day
df['DOJ'].dt.day_name()

0      Tuesday
1       Friday
2    Wednesday
3       Monday
4       Friday
5       Sunday
6       Friday
Name: DOJ, dtype: object

In [139]:
### add a  month columns values
df['month']=df['DOJ'].dt.month
df
df['Year']=df['DOJ'].dt.year
df

,name,age,salary,experiance,Team,bonus,increment,DOJ,month,Year
0,ganesh,13,20000,1,CEO,4000.0,24000.0,2024-01-23,1,2024
1,naik,34,33000,2,HR,6600.0,39600.0,2023-11-03,11,2023
2,nikki,55,4500,3,CTO,900.0,5400.0,2025-03-12,3,2025
3,mikki,33,5000,0,DA,1000.0,6000.0,2026-05-25,5,2026
4,gaike,32,3444,4,MANAGER,688.8,4132.8,2022-04-29,4,2022
5,gowda,44,3443,5,DEAN,688.6,4131.6,2023-08-13,8,2023
6,ABC,32,20300,2,DTO,4060.0,24360.0,2021-09-03,9,2021

In [141]:
### prohibitation date is + pd.datedelta(days= noof days)
df['DOJ']+pd.Timedelta(days=90)

0   2024-04-22
1   2024-02-01
2   2025-06-10
3   2026-08-23
4   2022-07-28
5   2023-11-11
6   2021-12-02
Name: DOJ, dtype: datetime64[ns]

### ***Handling Missing values***

In [143]:
df

,name,age,salary,experiance,Team,bonus,increment,DOJ,month,Year
0,ganesh,13,20000,1,CEO,4000.0,24000.0,2024-01-23,1,2024
1,naik,34,33000,2,HR,6600.0,39600.0,2023-11-03,11,2023
2,nikki,55,4500,3,CTO,900.0,5400.0,2025-03-12,3,2025
3,mikki,33,5000,0,DA,1000.0,6000.0,2026-05-25,5,2026
4,gaike,32,3444,4,MANAGER,688.8,4132.8,2022-04-29,4,2022
5,gowda,44,3443,5,DEAN,688.6,4131.6,2023-08-13,8,2023
6,ABC,32,20300,2,DTO,4060.0,24360.0,2021-09-03,9,2021

In [144]:
df.isnull()

,name,age,salary,experiance,Team,bonus,increment,DOJ,month,Year
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False

In [145]:
df

,name,age,salary,experiance,Team,bonus,increment,DOJ,month,Year
0,ganesh,13,20000,1,CEO,4000.0,24000.0,2024-01-23,1,2024
1,naik,34,33000,2,HR,6600.0,39600.0,2023-11-03,11,2023
2,nikki,55,4500,3,CTO,900.0,5400.0,2025-03-12,3,2025
3,mikki,33,5000,0,DA,1000.0,6000.0,2026-05-25,5,2026
4,gaike,32,3444,4,MANAGER,688.8,4132.8,2022-04-29,4,2022
5,gowda,44,3443,5,DEAN,688.6,4131.6,2023-08-13,8,2023
6,ABC,32,20300,2,DTO,4060.0,24360.0,2021-09-03,9,2021

In [147]:
import numpy as np
df.loc[df.name=='nikki','salary']=np.nan

In [148]:
df.loc[df.name=='gowda','salary']=np.nan

In [149]:
df

,name,age,salary,experiance,Team,bonus,increment,DOJ,month,Year
0,ganesh,13,20000.0,1,CEO,4000.0,24000.0,2024-01-23,1,2024
1,naik,34,33000.0,2,HR,6600.0,39600.0,2023-11-03,11,2023
2,nikki,55,NaN,3,CTO,900.0,5400.0,2025-03-12,3,2025
3,mikki,33,5000.0,0,DA,1000.0,6000.0,2026-05-25,5,2026
4,gaike,32,3444.0,4,MANAGER,688.8,4132.8,2022-04-29,4,2022
5,gowda,44,NaN,5,DEAN,688.6,4131.6,2023-08-13,8,2023
6,ABC,32,20300.0,2,DTO,4060.0,24360.0,2021-09-03,9,2021

In [150]:
df.isnull()

,name,age,salary,experiance,Team,bonus,increment,DOJ,month,Year
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
5,False,False,True,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False

In [151]:
df.describe()

,age,salary,experiance,bonus,increment,DOJ,month,Year
count,7.000000,5.00000,7.000000,7.000000,7.000000,7,7.000000,7.000000
mean,34.714286,16348.80000,2.428571,2562.485714,15374.914286,2023-11-15 00:00:00,5.857143,2023.428571
min,13.000000,3444.00000,0.000000,688.600000,4131.600000,2021-09-03 00:00:00,1.000000,2021.000000
25%,32.000000,5000.00000,1.500000,794.400000,4766.400000,2022-12-20 12:00:00,3.500000,2022.500000
50%,33.000000,20000.00000,2.000000,1000.000000,6000.000000,2023-11-03 00:00:00,5.000000,2023.000000
75%,39.000000,20300.00000,3.500000,4030.000000,24180.000000,2024-08-17 00:00:00,8.500000,2024.500000
max,55.000000,33000.00000,5.000000,6600.000000,39600.000000,2026-05-25 00:00:00,11.000000,2026.000000
std,12.828540,12263.10349,1.718249,2339.440252,14036.641510,NaN,3.579040,1.718249

In [152]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, 0 to 6
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        7 non-null      object
 1   age         7 non-null      int64
 2   salary      5 non-null      float64
 3   experiance  7 non-null      int64
 4   Team        7 non-null      object
 5   bonus       7 non-null      float64
 6   increment   7 non-null      float64
 7   DOJ         7 non-null      datetime64[ns]
 8   month       7 non-null      int32
 9   Year        7 non-null      int32
dtypes: datetime64[ns](1), float64(3), int32(2), int64(2), object(2)
memory usage: 728.0+ bytes

In [153]:
df.isnull().sum()

name          0
age           0
salary        2
experiance    0
Team          0
bonus         0
increment     0
DOJ           0
month         0
Year          0
dtype: int64

In [154]:
df.fillna(0)

,name,age,salary,experiance,Team,bonus,increment,DOJ,month,Year
0,ganesh,13,20000.0,1,CEO,4000.0,24000.0,2024-01-23,1,2024
1,naik,34,33000.0,2,HR,6600.0,39600.0,2023-11-03,11,2023
2,nikki,55,0.0,3,CTO,900.0,5400.0,2025-03-12,3,2025
3,mikki,33,5000.0,0,DA,1000.0,6000.0,2026-05-25,5,2026
4,gaike,32,3444.0,4,MANAGER,688.8,4132.8,2022-04-29,4,2022
5,gowda,44,0.0,5,DEAN,688.6,4131.6,2023-08-13,8,2023
6,ABC,32,20300.0,2,DTO,4060.0,24360.0,2021-09-03,9,2021

In [155]:
df.fillna(df['salary'].mean())

,name,age,salary,experiance,Team,bonus,increment,DOJ,month,Year
0,ganesh,13,20000.0,1,CEO,4000.0,24000.0,2024-01-23,1,2024
1,naik,34,33000.0,2,HR,6600.0,39600.0,2023-11-03,11,2023
2,nikki,55,16348.8,3,CTO,900.0,5400.0,2025-03-12,3,2025
3,mikki,33,5000.0,0,DA,1000.0,6000.0,2026-05-25,5,2026
4,gaike,32,3444.0,4,MANAGER,688.8,4132.8,2022-04-29,4,2022
5,gowda,44,16348.8,5,DEAN,688.6,4131.6,2023-08-13,8,2023
6,ABC,32,20300.0,2,DTO,4060.0,24360.0,2021-09-03,9,2021